include device/qcom/${platform}/${platform}.mk

PRODUCT_NAME := {TARGET_PRODUCT}
PRODUCT_DEVICE := {TARGET_PRODUCT}
PRODUCT_BRAND := asus
PRODUCT_MODEL := ASUS_{TARGET_PRODUCT}D
PRODUCT_MANUFACTURER := asus
TARGET_PROJECT ?= ${TARGET_PROJECT}
TARGET_VENDOR := asus

