-include device/qcom/msm8953_64/msm8953_64.mk
-include device/asus/common/common.mk

PRODUCT_NAME := Z01M
PRODUCT_DEVICE := Z01M
PRODUCT_BRAND := asus
PRODUCT_MODEL := ASUS_Z01MD
PRODUCT_MANUFACTURER := asus
TARGET_PROJECT ?= ZD552KL
BOARD_USES_LIBC_WRAPPER := true
